Gui
barinoffarseni/snake pull request #4
Opened 2023-11-23 15:33 UTC by barinoffarseni

Добавление выигрыша и проигрыша.

2023-11-23 15:41 UTC, newparadigma requested changes

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +WINDOW_WIDTH = 100
размер кона 100 пикселей?

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +    for event in pygame.event.get():
Это логика которая следит за нажатием крестика на окне и закроет игру если нажать, название функции close_game не соответсвует этой логике

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +pygame.init()
дубликат 28 строки

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +pygame.mixer.pre_init(44100, -16, 1, 512)
что это такое?

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +    audio_nambers = randrange(0, 3)
дубликат

2023-11-23 15:41 UTC, newparadigma commented on game.py
>      x += dx * SIZE
склеил 2 разных логики, добавь перенос строки

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +                        pygame.display.flip()
что делает эта функция?

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +                apple = get_new_apple_coordinates(snake)
склеил 2 разные логики - ставь перенос строки

2023-11-23 15:41 UTC, newparadigma commented on game.py
> +            # pygame.time.delay(50)
коммент удалить

2023-11-23 15:52 UTC, barinoffarseni commented on game.py
> +pygame.mixer.pre_init(44100, -16, 1, 512)
иницилизация

2023-11-23 15:57 UTC, barinoffarseni commented on game.py
>      x += dx * SIZE
не понял

2023-11-23 16:27 UTC, barinoffarseni commented on game.py
> +                        pygame.display.flip()
Она позволяет обновлять только часть экрана, а не всю область.

2023-11-23 18:07 UTC, newparadigma requested changes
ты мне отдал на ревью код который вообще на работает

2023-11-23 18:07 UTC, newparadigma commented on game.py
> +pygame.mixer.pre_init(44100, -16, 1, 512)
инициализация чего, что будет если ее убрать?

2023-11-23 18:07 UTC, newparadigma commented on game.py
>      x += dx * SIZE
49 и 50 строки идут без пустой строки между ними, а это 2 разные логики

2023-11-23 18:07 UTC, newparadigma commented on game.py
> +                        pygame.display.flip()
https://www.pygame.org/docs/ref/display.html#pygame.display.flip
вообще написано что всю область, но пофиг
крч это функция обновления данных отображаемых на экране

2023-11-23 18:14 UTC, barinoffarseni commented on game.py
> +pygame.mixer.pre_init(44100, -16, 1, 512)
pygame.init() инициализирует font какой то а если убрать то будет выёбываться
pygame.mixer.init() иницилизирует миксер и будет тоже самое

2023-11-24 10:42 UTC, newparadigma requested changes
В целом нужно будет сделать перестановку в коде, тк у тебя тут структурная ошибка

2023-11-24 10:42 UTC, newparadigma commented on game.py
> +pygame.mixer.pre_init(44100, -16, 1, 512)
Арсении мой комментарии к строке 32

2023-11-24 13:02 UTC, closed without merging