Design
barinoffarseni/snake pull request #7
Opened 2023-12-26 17:46 UTC by barinoffarseni

Добавление шахматного поля на фоне.
Добавление дизайна змейки.
Добавление дизайна яблока.

2023-12-26 17:53 UTC, newparadigma requested changes

2023-12-26 17:53 UTC, newparadigma commented on game.py
> +branch_width = 10
21 - 24 это константы, а не переменные
переменная означает что данные в ней могут меняться, если данные не меняются это константа

2023-12-26 17:53 UTC, newparadigma commented on game.py
> +                pygame.draw.rect(screen, light_reflection, (i, j, SIZE, SIZE))
вынеси всю логику отрисовок в отдельный фаил в виде функции

2024-01-27 14:49 UTC, newparadigma requested changes

2024-01-27 14:49 UTC, newparadigma commented on apple.py
> +        'x, y': (25, 25)
что такое x, y в контакте стилей не понятно
и ключ 'x, y' это фигня, нужно разделить на отдельно x отдельно y

2024-01-27 14:49 UTC, newparadigma commented on apple.py
> +        'x, y': (25, 25)
комментарии касается всех ключей  'x, y' которые вообще есть в проекте

2024-01-27 14:49 UTC, newparadigma commented on apple.py
> +  def draw_apple(self, screen, apple_branch_color, light_reflection, branch, apple, light_reflection_color, apple_color, apple_styles):
apple.draw_apple это тавтология(масло маслянное)
яблоко.рисовать_яблоко

измени на просто draw и огромное количество аргументов функции можно заменить на 1 self.

итого будет draw(self, screen)

2024-01-27 14:49 UTC, newparadigma commented on game.py
> +def get_new_apple_coordinates(snake, width, size):
функцию необходимо перенести в класс apple, и вместо snake аргументом будет ocupied_coordinates  - занятые координаты.

2024-01-27 14:49 UTC, newparadigma commented on game.py
> +apple = apple.Apple(apple_x, apple_y)
нужно сделать для apple логику что если x и y не передаются в класс при инициализации - то они создаются сами изнутри объекта

2024-01-27 14:49 UTC, newparadigma commented on game.py
> +    snake.draw(snake.snake_color, screen, SIZE)
не передавай в snake.draw первым аргументом snake.snake_color, тк метод draw класса snake и так получает self параметр по умолчанию, и из него ты можешь вытащить snake_color изнутри метода

2024-01-27 14:49 UTC, newparadigma commented on game.py
> +    eyes = snake.get_eyes_offset(snake.dy, snake.dx)
не передавай сам объект в метод этого объекта, используй self изнутри метода

2024-01-27 14:49 UTC, newparadigma commented on game.py
> +    snake.draw_eyes(eyes, screen, snake.eyes_colors, background_color, snake.eyes_width, snake.pupil_width)
не передавай сам объект в метод этого объекта, используй self изнутри метода

2024-01-27 14:49 UTC, newparadigma commented on game.py
> +            apple.x, apple.y = get_new_apple_coordinates(snake.segments, WINDOW_WIDTH, SIZE)
apple. set_new_coordinates(snake.segments, WINDOW_WIDTH, SIZE)
вместо этой строки

2024-01-27 14:49 UTC, newparadigma commented on game.py
> +    if 0 > x or x > WINDOW_WIDTH - SIZE or y < 0 or y > WINDOW_WIDTH - SIZE or len(snake.segments) != len(set(snake.segments)):
условие WINDOW_WIDTH - SIZE просчитывается каждый раз при тике, именно происходит арифметика.
вынеси WINDOW_WIDTH - SIZE в отдельную переменную ВНЕ цикла что бы не производить лишней арифметики

2024-01-27 14:49 UTC, newparadigma commented on snake.py
> +    def draw_snake(self, snake_color, screen, SIZE):
тоже самое что и я описал в комментарии к draw_apple

2024-03-19 17:36 UTC, newparadigma requested changes

2024-03-19 17:36 UTC, newparadigma commented on game.py
> +    snake.draw_eyes(eyes, screen, background_color)
snake.draw_eyes(eyes, screen, background_color)
функция draw_eyes не должна брать eyes из-вне, она должна вызвать функцию snake.get_eyes_offset() внутри себя

2024-03-19 17:36 UTC, newparadigma commented on apple.py
> +  def get_new_apple_coordinates(self, snake, width, size):
2ой параметр это должен быть список занятый клеток, а не snake тк если добавится еще одно яблоко то его координату тоже нужно будет передавать сюда первым параметром.

назови его busy_coordinates

2024-03-23 13:44 UTC, newparadigma requested changes

2024-03-23 13:44 UTC, newparadigma commented on game.py
> +apple_x, apple_y = randrange(0 ,WINDOW_WIDTH, SIZE) , randrange(0 ,WINDOW_WIDTH, SIZE)
убрать, логика должна сама срабатывать при создании нового яблока

2024-03-25 18:20 UTC, newparadigma requested changes

2024-03-25 18:20 UTC, newparadigma commented on apple.py
> +    self.x = randrange(0 ,width, size)
запятая не там где надо

2024-03-25 18:20 UTC, newparadigma commented on apple.py
> +    self.y = randrange(0 ,width, size)
запятая не там где надо

2024-03-25 18:20 UTC, newparadigma commented on apple.py
> +  def get_new_apple_coordinates(self, busy_coordinates, width, size):
не вижу использование этой функции в коде

2024-03-25 18:20 UTC, newparadigma commented on game.py
> +snake = snake.Snake(x, y)
тоже самое и с snake, генерит ее координаты можно изнутри из функции __init__ как у apple

2024-03-26 18:32 UTC, barinoffarseni commented on apple.py
> +  def get_new_apple_coordinates(self, busy_coordinates, width, size):
В game.py на 34 и 108 строке

2024-03-26 18:50 UTC, newparadigma approved these changes
Все ок

2024-03-26 18:51 UTC, merged